import intf_libs += libcrails%lib{crails}
import intf_libs += yaml-cpp%lib{yaml-cpp}

lib{crails-yaml-parser}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_YAML_PARSER_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_YAML_PARSER_SHARED_BUILD

# Export options.
#
lib{crails-yaml-parser}:
{
  cxx.export.poptions = "-I$out_root/libcrails-yaml-parser/" "-I$src_root/libcrails-yaml-parser/"
  cxx.export.libs = $intf_libs
}

liba{crails-yaml-parser}: cxx.export.poptions += -DLIBCRAILS_YAML_PARSER_STATIC
libs{crails-yaml-parser}: cxx.export.poptions += -DLIBCRAILS_YAML_PARSER_SHARED

if $version.pre_release
  lib{crails-yaml-parser}: bin.lib.version = "-$version.project_id"
else
  lib{crails-yaml-parser}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-yaml-parser/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
